import 'package:latlong2/latlong.dart';

/// 앱 전체(MAP, 추천, Archive) 공통 단일 데이터 소스.
class Attraction {
  final String id;
  final String name;
  final String category;     // '어트랙션' | '음식점' | '카페' | '포토스팟'
  final String zone;
  final double lat;
  final double lng;
  final bool indoor;
  /// 키 제한(cm). 0 = 제한 없음.
  final int heightLimit;
  /// 스릴 강도 1~5. (음식점은 0)
  final int thrillLevel;
  /// 예상 대기시간(분).
  final int waitMinutes;
  final double rating;
  final bool hasEasterEgg;
  /// 'spring' | 'summer' | 'autumn' | 'winter' | null
  final String? chapter;
  final String description;
  final String icon;
  final bool isOperating;
  /// 좌표 실측 검증 여부. false = zone-level 추정값 (베타 전 보정 필요).
  final bool coordsVerified;

  const Attraction({
    required this.id,
    required this.name,
    required this.category,
    required this.zone,
    required this.lat,
    required this.lng,
    required this.indoor,
    required this.heightLimit,
    required this.thrillLevel,
    required this.waitMinutes,
    required this.rating,
    required this.hasEasterEgg,
    required this.chapter,
    required this.description,
    required this.icon,
    required this.isOperating,
    this.coordsVerified = false,
  });

  LatLng get position => LatLng(lat, lng);

  String get crowdLabel {
    if (waitMinutes <= 5) return '여유';
    if (waitMinutes <= 20) return '보통';
    return '혼잡';
  }
}

// 좌표: 서울랜드 실제 위치(37.4279, 127.0247) 기준 테마존 추정값.
// 각 엔트리 coordsVerified=false → 베타 출시 전 현장 GPS / 운영팀 데이터로 보정 필요.
const List<Attraction> kAttractions = [
  Attraction(
    id: 'galaxy_888',
    name: '은하열차 888',
    category: '어트랙션',
    zone: '미래의 나라',
    lat: 37.4357, lng: 127.0209,
    indoor: false, heightLimit: 110, thrillLevel: 4, waitMinutes: 15,
    rating: 4.5, hasEasterEgg: true, chapter: 'autumn',
    description: '서울랜드 대표 스릴 어트랙션. 빠른 속도의 롤러코스터.',
    icon: '🎢', isOperating: true,
  ),
  Attraction(
    id: 'blackhole_2000',
    name: '블랙홀 2000',
    category: '어트랙션',
    zone: '미래의 나라',
    lat: 37.4354, lng: 127.0199,
    indoor: true, heightLimit: 120, thrillLevel: 5, waitMinutes: 25,
    rating: 4.7, hasEasterEgg: true, chapter: 'autumn',
    description: '어둠 속 스크류 코스터. 서울랜드 최고 스릴 어트랙션.',
    icon: '🌀', isOperating: true,
  ),
  Attraction(
    id: 'flume_ride',
    name: '급류타기',
    category: '어트랙션',
    zone: '세계의 광장',
    lat: 37.434, lng: 127.0193,
    indoor: false, heightLimit: 110, thrillLevel: 3, waitMinutes: 20,
    rating: 4.3, hasEasterEgg: true, chapter: 'summer',
    description: '물길을 따라 내려오는 보트 어트랙션.',
    icon: '🌊', isOperating: true,
  ),
  Attraction(
    id: 'gyro_swing',
    name: '알포스윙',
    category: '어트랙션',
    zone: '모험의 나라',
    lat: 37.4336, lng: 127.0203,
    indoor: false, heightLimit: 130, thrillLevel: 4, waitMinutes: 30,
    rating: 4.4, hasEasterEgg: false, chapter: 'autumn',
    description: '360도 회전하는 스윙 어트랙션.',
    icon: '🎡', isOperating: true,
  ),
  Attraction(
    id: 'carousel',
    name: '빅회전목마',
    category: '어트랙션',
    zone: '캐릭터 타운',
    lat: 37.4333, lng: 127.0181,
    indoor: false, heightLimit: 0, thrillLevel: 1, waitMinutes: 5,
    rating: 4.0, hasEasterEgg: true, chapter: 'spring',
    description: '1988년 개장 당시부터 함께한 서울랜드의 상징.',
    icon: '🎠', isOperating: true,
  ),
  Attraction(
    id: 'bumper_car',
    name: '카트라이더범퍼',
    category: '어트랙션',
    zone: '캐릭터 타운',
    lat: 37.433, lng: 127.0185,
    indoor: true, heightLimit: 0, thrillLevel: 2, waitMinutes: 15,
    rating: 4.1, hasEasterEgg: false, chapter: 'spring',
    description: '남녀노소 즐길 수 있는 실내 범퍼카.',
    icon: '🚗', isOperating: true,
  ),
  Attraction(
    id: 'viking',
    name: '킹바이킹',
    category: '어트랙션',
    zone: '모험의 나라',
    lat: 37.4339, lng: 127.02,
    indoor: false, heightLimit: 120, thrillLevel: 3, waitMinutes: 20,
    rating: 4.2, hasEasterEgg: true, chapter: 'summer',
    description: '좌우로 크게 흔들리는 해적선 어트랙션.',
    icon: '⚓', isOperating: true,
  ),
  Attraction(
    id: 'cpk_restaurant',
    name: '캘리포니아피자키친',
    category: '음식점',
    zone: '세계의 광장',
    lat: 37.4333, lng: 127.0186,
    indoor: true, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 3.8, hasEasterEgg: false, chapter: null,
    description: '캘리포니아 피자 키친. 피자·파스타 전문.',
    icon: '🍕', isOperating: true,
  ),
  // ─── 추가 어트랙션 (5) ──────────────────────────────────
  Attraction(
    id: 'sky_x',
    name: '스카이엑스',
    category: '어트랙션',
    zone: '미래의 나라',
    lat: 37.4355, lng: 127.0193,
    indoor: false, heightLimit: 130, thrillLevel: 5, waitMinutes: 30,
    rating: 4.6, hasEasterEgg: false, chapter: 'autumn',
    description: '70m 상공에서 자유낙하하는 익스트림 라이드.',
    icon: '🪂', isOperating: true,
  ),
  Attraction(
    id: 'time_machine_5d',
    name: '타임머신 5D 360',
    category: '어트랙션',
    zone: '미래의 나라',
    lat: 37.4346, lng: 127.0198,
    indoor: true, heightLimit: 0, thrillLevel: 2, waitMinutes: 12,
    rating: 4.0, hasEasterEgg: false, chapter: 'winter',
    description: '5D 입체 영상과 360도 회전 모션 체험.',
    icon: '🎬', isOperating: true,
  ),
  Attraction(
    id: 'ghost_cave',
    name: '미래의 골동품가게',
    category: '어트랙션',
    zone: '캐릭터 타운',
    lat: 37.4340, lng: 127.0185,
    indoor: true, heightLimit: 0, thrillLevel: 3, waitMinutes: 10,
    rating: 3.9, hasEasterEgg: true, chapter: 'winter',
    description: '으스스한 분위기의 다크 라이드.',
    icon: '👻', isOperating: true,
  ),
  Attraction(
    id: 'lava_twister',
    name: '라바트위스터',
    category: '어트랙션',
    zone: '모험의 나라',
    lat: 37.4342, lng: 127.0207,
    indoor: false, heightLimit: 120, thrillLevel: 4, waitMinutes: 18,
    rating: 4.3, hasEasterEgg: true, chapter: 'summer',
    description: '회전하는 용암 컵에 올라타는 스릴 라이드.',
    icon: '🌋', isOperating: true,
  ),
  // ─── 추가 음식점 (4) ────────────────────────────────────
  Attraction(
    id: 'santa_restaurant',
    name: '산타레스토랑',
    category: '음식점',
    zone: '캐릭터 타운',
    lat: 37.4329, lng: 127.0193,
    indoor: true, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.2, hasEasterEgg: false, chapter: null,
    description: '한식·양식 코스 메뉴.',
    icon: '🍽️', isOperating: true,
  ),
  // ─── 카페 (5) ───────────────────────────────────────────
  Attraction(
    id: 'cafe_bene',
    name: '카페베네 서울랜드점',
    category: '카페',
    zone: '캐릭터 타운',
    lat: 37.4326, lng: 127.0177,
    indoor: true, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.0, hasEasterEgg: false, chapter: null,
    description: '호수 뷰 베이커리 카페.',
    icon: '☕', isOperating: true,
  ),
  // ─── 포토스팟 (5) ───────────────────────────────────────
  Attraction(
    id: 'fountain_plaza',
    name: '중앙 분수 광장',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4344, lng: 127.0195,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.5, hasEasterEgg: true, chapter: 'summer',
    description: '시원한 물줄기 배경의 인생샷 명소.',
    icon: '⛲', isOperating: true,
  ),
  Attraction(
    id: 'flower_garden',
    name: '꽃 정원',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4348, lng: 127.0190,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.6, hasEasterEgg: false, chapter: 'spring',
    description: '계절꽃이 만개하는 정원.',
    icon: '🌷', isOperating: true,
  ),
  Attraction(
    id: 'lake_bridge',
    name: '호숫가 다리',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4337, lng: 127.0179,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.4, hasEasterEgg: false, chapter: 'autumn',
    description: '단풍 시즌 인생샷 명소.',
    icon: '🌉', isOperating: true,
  ),
  Attraction(
    id: 'night_view_deck',
    name: '미래의 나라 전망대',
    category: '포토스팟',
    zone: '미래의 나라',
    lat: 37.4357, lng: 127.0214,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.7, hasEasterEgg: true, chapter: 'winter',
    description: '야경과 불빛쇼 명소.',
    icon: '🌃', isOperating: true,
  ),
  // ─── 추가 어트랙션 (13) ─────────────────────────────────
  Attraction(
    id: 'shot_drop',
    name: '샷드롭',
    category: '어트랙션',
    zone: '미래의 나라',
    lat: 37.4353, lng: 127.0212,
    indoor: false, heightLimit: 130, thrillLevel: 4, waitMinutes: 22,
    rating: 4.3, hasEasterEgg: false, chapter: 'autumn',
    description: '순간 발사 후 자유낙하 반복.',
    icon: '🚀', isOperating: true,
  ),
  Attraction(
    id: 'x_flyer',
    name: 'X-플라이어',
    category: '어트랙션',
    zone: '모험의 나라',
    lat: 37.4344, lng: 127.0210,
    indoor: false, heightLimit: 130, thrillLevel: 4, waitMinutes: 20,
    rating: 4.2, hasEasterEgg: true, chapter: 'autumn',
    description: '엎드린 자세로 하늘을 가르는 플라잉 라이드.',
    icon: '🦅', isOperating: true,
  ),
  Attraction(
    id: 'mini_viking',
    name: '미니바이킹',
    category: '어트랙션',
    zone: '캐릭터 타운',
    lat: 37.4327, lng: 127.0185,
    indoor: false, heightLimit: 0, thrillLevel: 1, waitMinutes: 8,
    rating: 3.9, hasEasterEgg: false, chapter: 'spring',
    description: '유아·아동용 미니 해적선.',
    icon: '⚓', isOperating: true,
  ),
  Attraction(
    id: 'shooting_adventure',
    name: '사격장',
    category: '어트랙션',
    zone: '모험의 나라',
    lat: 37.4346, lng: 127.0205,
    indoor: true, heightLimit: 0, thrillLevel: 2, waitMinutes: 8,
    rating: 4.1, hasEasterEgg: false, chapter: 'winter',
    description: '광선총으로 타겟을 맞추는 슈팅형 라이드.',
    icon: '🎯', isOperating: true,
  ),
  Attraction(
    id: 'mini_airplane',
    name: '깜부비행기',
    category: '어트랙션',
    zone: '캐릭터 타운',
    lat: 37.4331, lng: 127.0182,
    indoor: false, heightLimit: 0, thrillLevel: 1, waitMinutes: 6,
    rating: 3.9, hasEasterEgg: false, chapter: 'spring',
    description: '하늘을 빙글빙글 도는 비행기.',
    icon: '✈️', isOperating: true,
  ),
  // ─── 추가 음식점 (6) ────────────────────────────────────
  Attraction(
    id: 'lotteria',
    name: '롯데리아 서울랜드점',
    category: '음식점',
    zone: '세계의 광장',
    lat: 37.4336, lng: 127.0184,
    indoor: true, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 3.7, hasEasterEgg: false, chapter: null,
    description: '버거·치킨·세트메뉴.',
    icon: '🍔', isOperating: true,
  ),
  Attraction(
    id: 'ramen_house',
    name: '캐루셀라멘',
    category: '음식점',
    zone: '세계의 광장',
    lat: 37.4341, lng: 127.0188,
    indoor: true, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.0, hasEasterEgg: false, chapter: null,
    description: '돈코츠·미소·시오 라멘.',
    icon: '🍜', isOperating: true,
  ),
  // ─── 추가 카페 ──────────────────────────────────────────
  Attraction(
    id: 'dunkin',
    name: '던킨도너츠',
    category: '카페',
    zone: '세계의 광장',
    lat: 37.4339, lng: 127.0183,
    indoor: true, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 3.9, hasEasterEgg: false, chapter: null,
    description: '도넛과 커피.',
    icon: '🍩', isOperating: true,
  ),
  // ─── 추가 포토스팟 ──────────────────────────────────────
  Attraction(
    id: 'main_gate_arch',
    name: '정문 아치',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4332, lng: 127.0175,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.2, hasEasterEgg: false, chapter: 'spring',
    description: '서울랜드 입장 인증샷 1번지.',
    icon: '🏛️', isOperating: true,
  ),
  Attraction(
    id: 'center_clock_tower',
    name: '중앙 시계탑',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4342, lng: 127.0193,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.1, hasEasterEgg: false, chapter: null,
    description: '광장 한가운데 랜드마크.',
    icon: '🕰️', isOperating: true,
  ),
  Attraction(
    id: 'earth_globe',
    name: '지구본 조형물',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4341, lng: 127.0196,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.0, hasEasterEgg: false, chapter: null,
    description: '대형 지구의 옆에서 포즈.',
    icon: '🌍', isOperating: true,
  ),
  Attraction(
    id: 'seoulland_sign',
    name: 'SEOULLAND 사인보드',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4334, lng: 127.0179,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.4, hasEasterEgg: false, chapter: null,
    description: '대형 알파벳 사인.',
    icon: '🔠', isOperating: true,
  ),
  Attraction(
    id: 'moonlight_garden',
    name: '달빛 정원',
    category: '포토스팟',
    zone: '미래의 나라',
    lat: 37.4354, lng: 127.0210,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.5, hasEasterEgg: true, chapter: 'winter',
    description: '야간 조명으로 빛나는 산책로.',
    icon: '🌙', isOperating: true,
  ),
  Attraction(
    id: 'cherry_blossom_path',
    name: '벚꽃길',
    category: '포토스팟',
    zone: '삼천리 동산',
    lat: 37.4347, lng: 127.0178,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.7, hasEasterEgg: false, chapter: 'spring',
    description: '4월 한정 벚꽃 터널.',
    icon: '🌸', isOperating: true,
  ),
  Attraction(
    id: 'autumn_maple_road',
    name: '단풍길',
    category: '포토스팟',
    zone: '삼천리 동산',
    lat: 37.4346, lng: 127.0175,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.6, hasEasterEgg: false, chapter: 'autumn',
    description: '10~11월 빨간 단풍 산책로.',
    icon: '🍁', isOperating: true,
  ),
  Attraction(
    id: 'rose_garden',
    name: '장미정원',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4349, lng: 127.0188,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.4, hasEasterEgg: false, chapter: 'summer',
    description: '5~6월 장미 만개.',
    icon: '🌹', isOperating: true,
  ),
  Attraction(
    id: 'waterfall_view',
    name: '폭포 전망대',
    category: '포토스팟',
    zone: '모험의 나라',
    lat: 37.4345, lng: 127.0213,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.3, hasEasterEgg: false, chapter: 'summer',
    description: '인공 폭포 앞 무지개 포토존.',
    icon: '💦', isOperating: true,
  ),
  Attraction(
    id: 'pirate_ship_view',
    name: '해적선 뷰포인트',
    category: '포토스팟',
    zone: '모험의 나라',
    lat: 37.4340, lng: 127.0201,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.0, hasEasterEgg: false, chapter: 'summer',
    description: '바이킹 배경 다이내믹 샷.',
    icon: '🏴‍☠️', isOperating: true,
  ),
  Attraction(
    id: 'world_flag_plaza',
    name: '세계국기 광장',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4337, lng: 127.0182,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.1, hasEasterEgg: false, chapter: null,
    description: '만국기 아래 인증샷.',
    icon: '🚩', isOperating: true,
  ),
  Attraction(
    id: 'dragon_statue',
    name: '용 조형물',
    category: '포토스팟',
    zone: '삼천리 동산',
    lat: 37.4345, lng: 127.0182,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.2, hasEasterEgg: true, chapter: 'autumn',
    description: '전통 황룡상.',
    icon: '🐉', isOperating: true,
  ),
  Attraction(
    id: 'fantasy_castle',
    name: '환상의 성',
    category: '포토스팟',
    zone: '캐릭터 타운',
    lat: 37.4330, lng: 127.0187,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.5, hasEasterEgg: false, chapter: 'winter',
    description: '동화 속 성을 닮은 외관.',
    icon: '🏰', isOperating: true,
  ),
  Attraction(
    id: 'tunnel_of_lights',
    name: '라이트 터널',
    category: '포토스팟',
    zone: '미래의 나라',
    lat: 37.4356, lng: 127.0203,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.6, hasEasterEgg: true, chapter: 'winter',
    description: '겨울 시즌 LED 터널.',
    icon: '💡', isOperating: true,
  ),
  Attraction(
    id: 'retro_phone_booth',
    name: '빨간 전화 부스',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4338, lng: 127.0186,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.0, hasEasterEgg: true, chapter: null,
    description: '런던풍 레트로 부스.',
    icon: '☎️', isOperating: true,
  ),
  Attraction(
    id: 'astronaut_statue',
    name: '우주인 조형물',
    category: '포토스팟',
    zone: '미래의 나라',
    lat: 37.4352, lng: 127.0199,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.2, hasEasterEgg: true, chapter: 'winter',
    description: '실물 크기 우주인 모형.',
    icon: '👨‍🚀', isOperating: true,
  ),
  Attraction(
    id: 'dinosaur_statue',
    name: '공룡 조형물',
    category: '포토스팟',
    zone: '모험의 나라',
    lat: 37.4344, lng: 127.0215,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.3, hasEasterEgg: false, chapter: 'summer',
    description: '대형 티라노 모형.',
    icon: '🦖', isOperating: true,
  ),
  Attraction(
    id: 'neon_sign_wall',
    name: '네온 사인 월',
    category: '포토스팟',
    zone: '미래의 나라',
    lat: 37.4350, lng: 127.0212,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.4, hasEasterEgg: false, chapter: 'winter',
    description: '네온사인 인생샷 월.',
    icon: '🟣', isOperating: true,
  ),
  Attraction(
    id: 'lake_pier',
    name: '호수 선착장',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4336, lng: 127.0177,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.3, hasEasterEgg: false, chapter: 'autumn',
    description: '호수 위 나무 데크.',
    icon: '⛵', isOperating: true,
  ),
  Attraction(
    id: 'cosmos_walk',
    name: '코스모스길',
    category: '포토스팟',
    zone: '삼천리 동산',
    lat: 37.4348, lng: 127.0176,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.5, hasEasterEgg: false, chapter: 'autumn',
    description: '9~10월 코스모스 만개.',
    icon: '🌼', isOperating: true,
  ),
  Attraction(
    id: 'tulip_garden',
    name: '튤립 정원',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4346, lng: 127.0192,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.5, hasEasterEgg: false, chapter: 'spring',
    description: '4~5월 튤립 만개.',
    icon: '🌷', isOperating: true,
  ),
  Attraction(
    id: 'firework_deck',
    name: '불꽃놀이 데크',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4343, lng: 127.0186,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.7, hasEasterEgg: false, chapter: 'summer',
    description: '주말 야간 불꽃 명당.',
    icon: '🎆', isOperating: true,
  ),
  Attraction(
    id: 'parade_archway',
    name: '퍼레이드 아치',
    category: '포토스팟',
    zone: '세계의 광장',
    lat: 37.4335, lng: 127.0188,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.2, hasEasterEgg: true, chapter: null,
    description: '오후 퍼레이드 통과 지점.',
    icon: '🎉', isOperating: true,
  ),
  Attraction(
    id: 'windmill_garden',
    name: '풍차 정원',
    category: '포토스팟',
    zone: '삼천리 동산',
    lat: 37.4351, lng: 127.0184,
    indoor: false, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.3, hasEasterEgg: true, chapter: 'spring',
    description: '네덜란드풍 미니 풍차.',
    icon: '🌾', isOperating: true,
  ),
  Attraction(
    id: 'mirror_maze',
    name: '거울 미로',
    category: '포토스팟',
    zone: '캐릭터 타운',
    lat: 37.4327, lng: 127.0190,
    indoor: true, heightLimit: 0, thrillLevel: 0, waitMinutes: 0,
    rating: 4.0, hasEasterEgg: true, chapter: 'winter',
    description: '무한 반사 거울방.',
    icon: '🪞', isOperating: true,
  ),
];

/// 챕터별 대상 어트랙션 ID. 챕터 내 이스터에그 어트랙션 전부 발견 → 챕터 완료.
const Map<String, List<String>> kChapterTargets = {
  'spring': ['cherry_blossom_path', 'carousel', 'bumper_car', 'mini_viking', 'viking'],
  'summer': ['flume_ride', 'sky_x', 'viking', 'bumper_car', 'shot_drop'],
  'autumn': ['galaxy_888', 'blackhole_2000', 'gyro_swing', 'shot_drop', 'viking'],
  'winter': ['carousel', 'santa_restaurant', 'bumper_car', 'blackhole_2000', 'time_machine_5d'],
};
